# Generated by Django 4.1.5 on 2023-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_id', models.CharField(max_length=70)),
                ('hatchery_id', models.CharField(max_length=100)),
                ('accreditation_agency', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=70)),
                ('year_of_accreditation', models.CharField(max_length=70)),
            ],
        ),
    ]
