# Generated by Django 4.1.5 on 2023-02-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_user_accreditation_id_alter_user_hatchery_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='broodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_id', models.IntegerField()),
                ('broodstock_type', models.CharField(max_length=70)),
                ('name_broodstock', models.CharField(max_length=70)),
                ('mgt_procedure_broodstock', models.IntegerField()),
                ('no_ponds_broodstock', models.CharField(max_length=70)),
                ('no_spawn_produce', models.CharField(max_length=70)),
                ('species_id', models.IntegerField()),
                ('no_fry_producing', models.IntegerField()),
                ('no_nursery_ponds', models.CharField(max_length=70)),
            ],
        ),
    ]
