# Generated by Django 4.1.5 on 2023-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_broodstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_id', models.IntegerField()),
                ('clients', models.CharField(max_length=70)),
                ('years', models.IntegerField()),
                ('clients_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_id', models.IntegerField()),
                ('cost_spawn', models.CharField(max_length=70)),
                ('cost_fry', models.CharField(max_length=70)),
                ('cost_fingerling', models.IntegerField()),
                ('cost_yearling', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hatchery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_id', models.IntegerField()),
                ('hatchery_name', models.CharField(max_length=70)),
                ('hatchery_type', models.CharField(max_length=70)),
                ('hatchery_category', models.IntegerField()),
                ('ownership', models.CharField(max_length=70)),
                ('owner_name', models.CharField(max_length=70)),
                ('hatchery_address', models.CharField(max_length=70)),
                ('species_breeding', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.IntegerField()),
                ('production_seed_type', models.CharField(max_length=70)),
                ('broodstock_id', models.IntegerField()),
                ('no_ponds_mgt', models.IntegerField()),
                ('tech_seed_production', models.CharField(max_length=70)),
                ('seed_production_year', models.CharField(max_length=70)),
                ('mgt_procedures', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_id', models.IntegerField()),
                ('spawn_sale_year', models.CharField(max_length=70)),
                ('fry_sale_year', models.CharField(max_length=70)),
                ('fingerling_sale_year', models.IntegerField()),
                ('yearling_sale_year', models.IntegerField()),
                ('species_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField()),
                ('hatchery_id', models.IntegerField()),
                ('species_name', models.CharField(max_length=70)),
            ],
        ),
    ]
