# Generated by Django 4.1.5 on 2023-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_cliental_cost_hatchery_production_sale_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_id', models.IntegerField()),
                ('hatchery_id', models.IntegerField()),
                ('accreditation_agency', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=70)),
                ('year_of_accreditation', models.IntegerField()),
            ],
        ),
    ]
